version: "3.9"
services:
  api:
    build: ./app
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    network_mode: host
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest  # successor of rtsp-simple-server
    network_mode: host
    restart: unless-stopped