version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"  # RTSP
      - "8889:8889"  # Web interface
      - "8890:8890"  # WebRTC
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml
      - ./logs:/logs
    restart: unless-stopped
    privileged: true

  camera-api:
    build: .
    container_name: camera-api
    ports:
      - "8000:8000"
    volumes:
      - /dev:/dev
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - MEDIAMTX_HOST=mediamtx
      - MEDIAMTX_PORT=8554
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      - mediamtx
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    cap_add:
      - SYS_ADMIN