version: '3.8'

services:
  picamera2:
    build: .
    stdin_open: true
    tty: true
    container_name: picamera2
    volumes:
      - ./code:/code
      - /run/udev/:/run/udev:ro
    devices:
      - /dev/video0:/dev/video0
    command: bash
    privileged: true
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"  # RTSP
      - "8889:8889"  # Web interface
      - "8890:8890"  # WebRTC
      - "9997:9997"  # API
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml
      - ./logs:/logs
    restart: unless-stopped
    networks:
      - camera-net

  camera-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camera-api
    ports:
      - "8000:8000"
    volumes:
      - /dev:/dev
      - ./config:/app/config
      - ./logs:/app/logs
      - /run/udev:/run/udev:ro
    environment:
      - MEDIAMTX_HOST=mediamtx
      - MEDIAMTX_PORT=8554
      - MEDIAMTX_API_PORT=9997
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      - mediamtx
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
    group_add:
      - video
    networks:
      - camera-net

networks:
  camera-net:
    driver: bridge