services:
  pi-camera-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/vchiq:/dev/vchiq"

    environment:
      - PYTHONUNBUFFERED=1
    privileged: true
    restart: unless-stopped
    networks:
      - camera-network

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554"  # RTSP
      - "1935:1935"  # RTMP
      - "8888:8888"  # HLS
      - "9997:9997"  # Web UI
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    networks:
      - camera-network

networks:
  camera-network:
    driver: bridge